In [80]:
import numpy as np
import math

In [125]:
coords = np.empty((0))
with open("unitcell", "r") as file:
    for line in file.readlines()[2:]:
        line_s = line.split()
        if line_s[0] != "HETATM":
            break
        #print(line_s[5:8])line_s[5:8]
        coords = np.append(coords, np.array(line_s[5:8],dtype=float))

coords = coords.reshape(-1,3)

def CalcUnitCell(coords):
    def ShiftOrigin(coords):
        coordsT = coords.T
        x_min, y_min, z_min = coordsT[0].min() , coordsT[1].min(), coordsT[2].min()
        coordsT[0], coordsT[1], coordsT[2] = coordsT[0] + abs(x_min), coordsT[1] + abs(y_min), coordsT[2] + abs(z_min)
        return coordsT.T
    
    shiftedCoords = ShiftOrigin(coords)
    
    x_max, y_max, z_max = shiftedCoords.T[0].max() , shiftedCoords.T[1].max(), shiftedCoords.T[2].max()
    return shiftedCoords, (x_max, y_max, z_max)

coords , cell  = CalcUnitCell(coords)
x_offset = 15
atomsWritten = 0
with open("unitcell", "r") as file:
    with open("write", "w") as writer:
        for i,line in enumerate(file.readlines()):
            if i == 2:
                writer.write(f"CRYST1   {math.ceil(cell[0])+x_offset}.000   {math.ceil(cell[1])}.000   {math.ceil(cell[2])}.000  90.00  90.00  90.00 P 1           1\n")
            if line.startswith(("HETATM", "ATM")):
                lineS = line.split()  
                writer.write(f"{lineS[0]}   {lineS[1]:>2}  {lineS[2]}   {lineS[3]}     {lineS[4]}      {coords[atomsWritten][0]:.3f}  {coords[atomsWritten][1]:.3f}  {coords[atomsWritten][2]:.3f}  {lineS[8]}  {lineS[9]}           {lineS[10]}\n")  
                atomsWritten += 1
            else:
                writer.write(line)

[[ 0.756  7.089  2.813]
 [ 0.398  5.973  2.077]
 [ 1.004  4.56   3.926]
 [ 1.334  5.683  4.666]
 [ 1.223  6.947  4.11 ]
 [ 0.652  8.068  2.381]
 [ 0.     6.071  1.083]
 [ 1.088  3.581  4.36 ]
 [ 1.679  5.567  5.678]
 [ 1.487  7.815  4.687]
 [ 0.075  3.603  1.844]
 [ 0.735  2.613  1.589]
 [ 2.116  2.456  1.938]
 [ 3.102  3.359  1.566]
 [ 2.47   1.258  2.54 ]
 [ 4.43   3.077  1.829]
 [ 2.839  4.274  1.07 ]
 [ 3.796  0.988  2.829]
 [ 1.703  0.546  2.782]
 [ 4.776  1.898  2.469]
 [ 5.202  3.771  1.551]
 [ 4.078  0.076  3.322]
 [ 0.554  4.708  2.622]
 [ 6.083  1.642  2.763]
 [ 6.813  0.959  1.771]
 [ 6.828  1.532  0.85 ]
 [ 6.352  0.     1.557]
 [ 8.203  0.767  2.286]
 [ 8.747  1.095  3.486]
 [ 9.164  0.178  1.542]
 [ 8.342  1.565  4.354]
 [10.024  0.679  3.391]
 [10.241  0.131  2.215]
 [11.097  0.777  4.365]
 [10.727  0.39   5.306]
 [11.875  0.114  4.017]
 [11.633  2.192  4.581]
 [10.828  2.865  4.861]
 [12.306  2.15   5.431]
 [12.431  2.796  3.428]
 [13.189  3.843  4.014]
 [13.116  2.06  